name: CI

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Run cargo fmt
        run: |
          cargo fmt --all -- --check

      - name: Run Clippy
        run: |
          cargo clippy --all -- -D warnings

      - name: Run clang-format
        uses: jidicula/clang-format-action@v4.15.0
        with:
          clang-format-version: '16'
          check-path: cpp
          exclude-regex: '(cpp/src/zngur_tvtf|build-.*|cpp/zngur)' # generated code

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # macos-14 for M1 runners
          - macos-14
          - ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - uses: taiki-e/install-action@nextest

      - name: Build
        run: cargo build

      - name: nextest
        run: cargo nextest run --profile ci

      - name: Upload JUnit report
        # Run this step even if the test step fails. Upload it right now because
        # we're most interested in the JUnit report generated by the local
        # version of nextest, not the latest release.
        if: '!cancelled()'
        uses: actions/upload-artifact@v4.6.2
        with:
          retention-days: 7
          name: junit-${{ matrix.os }}.xml
          path: |
            target/nextest/ci/junit.xml
          if-no-files-found: error

      - name: Upload nextest binary
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          retention-days: 7
          compression-level: 9
          name: cargo-nextest-${{ matrix.os }}
          path: |
            target/debug/librust_tvtf.dylib
            target/debug/librust_tvtf.so
            target/debug/librust_tvtf.d
            cpp/zngur_tvtf/generated.h
            cpp/zngur_tvtf/extra_generated.h
          if-no-files-found: error
