name: Publish releases to GitHub
on:
  push:
    tags:
      - '[0-9]+.*'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build-binaries:
    name: Build binaries for ${{ matrix.target }}
    if: github.repository_owner == 'yanhuangdata'
    strategy:
      matrix:
        include:
          # Native builds
          - target: aarch64-apple-darwin
            # macos-14 for M1 runners
            os: macos-14
            build-target: aarch64-apple-darwin

          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            build-target: x86_64-unknown-linux-gnu

          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
            build-target: aarch64-unknown-linux-gnu

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Install Rust
        uses: dsherret/rust-toolchain-file@v1
      - name: Test
        run: |
          cargo build --release --target ${{ matrix.build-target }}

      - name: Build and package release
        run: |
          ./ci/scripts/pack-release.sh "${{ matrix.build-target }}" "rust_tvtf" "${{ env.RELEASE_VERSION }}"
          ./ci/scripts/pack-release.sh "${{ matrix.build-target }}" "rust_tvtf_example" "${{ env.RELEASE_VERSION }}"

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            cpp/zngur/extra_generated.h
            cpp/zngur/generated.h
            rust_tvtf-${{ env.RELEASE_VERSION }}-${{ matrix.build-target }}.tar.gz
            rust_tvtf-${{ env.RELEASE_VERSION }}-${{ matrix.build-target }}.tar.gz.sha256
            rust_tvtf_example-${{ env.RELEASE_VERSION }}-${{ matrix.build-target }}.tar.gz
            rust_tvtf_example-${{ env.RELEASE_VERSION }}-${{ matrix.build-target }}.tar.gz.sha256
          draft: true
          tag_name: ${{ env.RELEASE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
